const gruposData = [
   {sede:"KENNEDY", lugar:"AUDITORIO PRINCIPAL", grupos:208, crec:181, warriors:7, relevo:20},
  {sede:"FONTIBÓN / ENGATIVÁ", lugar:"AUDITORIO PRINCIPAL", grupos:103, crec:98, warriors:0, relevo:5},
  {sede:"BOSA", lugar:"AUDITORIO PRINCIPAL", grupos:84, crec:75, warriors:1, relevo:6},
  {sede:"INTERLOCALIDADES", lugar:"AUDITORIO PRINCIPAL", grupos:1, crec:1, warriors:0, relevo:0},

  {sede:"TEJAR", lugar:"SEDES BOGOTÁ", grupos:136, crec:126, warriors:0, relevo:6},
  {sede:"CIUDAD BOLIVAR", lugar:"SEDES BOGOTÁ", grupos:112, crec:112, warriors:0, relevo:0},
  {sede:"SOACHA", lugar:"SEDES BOGOTÁ", grupos:103, crec:103, warriors:0, relevo:0},
  {sede:"USME", lugar:"SEDES BOGOTÁ", grupos:95, crec:95, warriors:0, relevo:0},
  {sede:"NORTE", lugar:"SEDES BOGOTÁ", grupos:97, crec:96, warriors:0, relevo:1},
  {sede:"FUNZA", lugar:"SEDES BOGOTÁ", grupos:41, crec:41, warriors:0, relevo:0},
  {sede:"RIONEGRO", lugar:"SEDES BOGOTÁ", grupos:37, crec:36, warriors:0, relevo:1},
  {sede:"SAN CRISTÓBAL", lugar:"SEDES BOGOTÁ", grupos:23, crec:22, warriors:0, relevo:0},
  {sede:"FACATATIVÁ", lugar:"SEDES BOGOTÁ", grupos:20, crec:20, warriors:0, relevo:0},
  {sede:"SABANA", lugar:"SEDES BOGOTÁ", grupos:19, crec:18, warriors:0, relevo:1},
  {sede:"UBATÉ", lugar:"SEDES BOGOTÁ", grupos:5, crec:5, warriors:0, relevo:0},

  {sede:"VALLEDUPAR", lugar:"SEDES NACIONALES", grupos:88, crec:88, warriors:0, relevo:0},
  {sede:"GIRARDOT", lugar:"SEDES NACIONALES", grupos:57, crec:57, warriors:0, relevo:0},
  {sede:"PITALITO", lugar:"SEDES NACIONALES", grupos:25, crec:25, warriors:0, relevo:0},
  {sede:"SAN SEBASTIAN", lugar:"SEDES NACIONALES", grupos:25, crec:24, warriors:1, relevo:1},
  {sede:"MANIZALES", lugar:"SEDES NACIONALES", grupos:23, crec:23, warriors:0, relevo:0},
  {sede:"IBAGUE", lugar:"SEDES NACIONALES", grupos:20, crec:20, warriors:0, relevo:0},
  {sede:"MONTERIA", lugar:"SEDES NACIONALES", grupos:19, crec:19, warriors:0, relevo:0},
  {sede:"CODAZZI", lugar:"SEDES NACIONALES", grupos:15, crec:13, warriors:0, relevo:2},
  {sede:"ARMENIA", lugar:"SEDES NACIONALES", grupos:13, crec:13, warriors:0, relevo:0},
  {sede:"ESPINAL", lugar:"SEDES NACIONALES", grupos:12, crec:12, warriors:0, relevo:0},
  {sede:"SANTA ROSA DEL SUR", lugar:"SEDES NACIONALES", grupos:12, crec:11, warriors:1, relevo:0},
  {sede:"SAN JOSE DEL GUAVIARE", lugar:"SEDES NACIONALES", grupos:12, crec:12, warriors:0, relevo:0},
  {sede:"PEREIRA", lugar:"SEDES NACIONALES", grupos:9, crec:9, warriors:0, relevo:0},
  {sede:"MEDELLÍN", lugar:"SEDES NACIONALES", grupos:0, crec:6, warriors:0, relevo:1},
  {sede:"HONDA", lugar:"SEDES NACIONALES", grupos:6, crec:6, warriors:0, relevo:0},
  {sede:"PUERTO LEGUIZAMO", lugar:"SEDES NACIONALES", grupos:6, crec:6, warriors:0, relevo:0},
  {sede:"MARSELLA", lugar:"SEDES NACIONALES", grupos:6, crec:6, warriors:0, relevo:0},
  {sede:"TUNJA", lugar:"SEDES NACIONALES", grupos:0, crec:6, warriors:0, relevo:0},
  {sede:"LA MESA", lugar:"SEDES NACIONALES", grupos:3, crec:3, warriors:0, relevo:0},
  {sede:"GUADUAS", lugar:"SEDES NACIONALES", grupos:2, crec:2, warriors:0, relevo:0},

  {sede:"NACIONAL", lugar:"ON LINE", grupos:1, crec:1, warriors:0, relevo:0},
  {sede:"INTERNACIONAL", lugar:"ON LINE", grupos:1, crec:1, warriors:0, relevo:0}
];
